[colors]
[colors.primary]
background = "#00000e"
foreground = "#c7efe3"

[colors.normal]
black   = "#00000e"
red     = "#ff4d6d"
green   = "#00d4a8"
yellow  = "#ffd166"
blue    = "#7186fd"
magenta = "#b388ff"
cyan    = "#00cfe8"
white   = "#c7efe3"

[colors.bright]
black   = "#5f6167"
red     = "#ff6f8f"
green   = "#33f0c0"
yellow  = "#ffe085"
blue    = "#5cb7ff"
magenta = "#c7a6ff"
cyan    = "#3aeaff"
white   = "#e6fff7"

[colors.cursor]
text   = "#00000e"
cursor = "#c7efe3"
