# Background and foreground colors
background = #00000e
foreground = #c7efe3

# Standard colors
palette = 0=#00000e
palette = 1=#ff4d6d
palette = 2=#00d4a8
palette = 3=#ffd166
palette = 4=#7186fd
palette = 5=#b388ff
palette = 6=#00cfe8
palette = 7=#c7efe3

# Bright colors
palette = 8=#5f6167
palette = 9=#ff6f8f
palette = 10=#33f0c0
palette = 11=#ffe085
palette = 12=#5cb7ff
palette = 13=#c7a6ff
palette = 14=#3aeaff
palette = 15=#e6fff7
