# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

$activeBorderColor = rgb(7186fd)
$activeShadowColor = rgb(8496fd)
$inactiveBorderColor = rgba(00000eba)
$inactiveShadowColor = rgba(00000ea6)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
    gaps_in = 0
    gaps_out = 0
    border_size = 1
    # Use master layout instead of dwindle
    layout = scrolling
    # allow_tearing = true
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}

decoration {
    rounding = 0
    blur {
        enabled = true
        size = 5
        passes = 2
        new_optimizations = true
        vibrancy = 0.2
        ignore_opacity = false
      }
      shadow {
          enabled = true
          range = 16
          render_power = 4
          color = $activeShadowColor
          color_inactive = $inactiveShadowColor
        }
  }

# Makes keepassxc float
windowrule {
    name = keepass-window
        match:class = org.keepassxc.KeePassXC
        float = true
        pin = true
}

windowrule {
    name = floating-window
        match:float = true
        border_size = 2
        rounding = 4
        # border_color = rgba(518a51ee)
        center = true
}

windowrule {
    name = modal-window
        match:modal = true
        border_size = 2
        rounding = 4
        # border_color = rgba(518a51ee)
        float = true
        center = true
}

# Config For scrolling and overview plugin
scrolling {
    fullscreen_on_one_column = true
    column_width = 1
    focus_fit_method = 1
    follow_focus = true
}
