$color = rgba(0, 0, 14, 1)
$inner_color = rgba(0, 0, 14, 0.66)
$outer_color = rgba(179, 136, 255, 1)
$font_color = rgba(199, 239, 227, 1)
$placeholder_color = rgba(199, 239, 227, 0.7)
$check_color = rgba(0, 207, 232, 1)
