background            #00000e
foreground            #c7efe3

# black
color0  #00000e
color8  #5f6167

# red
color1  #ff4d6d
color9  #ff6f8f

# green
color2  #00d4a8
color10 #33f0c0

# yellow
color3  #ffd166
color11 #ffe085

# blue
color4  #7186fd
color12 #5cb7ff

# magenta
color5  #b388ff
color13 #c7a6ff

#cyan
color6  #00cfe8
color14 #3aeaff

#white
color7  #c7efe3
color15 #e6fff7


